---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  namespace: networkpolicy-leaf1
  labels:
    app: foo
spec:
  selector:
    matchLabels:
      app: foo
  replicas: 1
  template:
    metadata:
      labels:
        app: foo
      annotations:
    spec:
      containers:
        - name: foo
          image: docker.io/sholly/foo:1.0
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /deployments/config
            name: foo-volume
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8778
              name: jolokia
              protocol: TCP
            - containerPort: 9779
              name: prometheus
              protocol: TCP
          # env:
          #   - name: SPRING_PROFILES_ACTIVE
          #     value: openshift
      volumes:
      - configMap:
          defaultMode: 420
          name: foo
        name: foo-volume
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: foo
  name: foo
  namespace: networkpolicy-leaf1
spec:
  ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 8080
  selector:
    app: foo
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: foo
  name: foo
  namespace: networkpolicy-leaf1
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: foo
    weight: 100
  wildcardPolicy: None
---
apiVersion: v1
data:
  application.properties: |-
    spring.application.name=foo
    server.port=8080
    management.endpoints.web.exposure.include=*
    leaf2.hostname=leaf2.networkpolicy-leaf2.svc
    leaf2.portnum=8080
    opentracing.jaeger.enabled=false
kind: ConfigMap
metadata:
  name: foo
  namespace: networkpolicy-leaf1
