---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaf1
  namespace: networkpolicy-leaf1
  labels:
    app: foo
spec:
  selector:
    matchLabels:
      app: leaf1
  replicas: 1
  template:
    metadata:
      labels:
        app: leaf1
      annotations:
    spec:
      containers:
        - name: leaf1
          image: docker.io/sholly/servicemesh-leaf1:1.0
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /deployments/config
            name: leaf1-volume
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8778
              name: jolokia
              protocol: TCP
            - containerPort: 9779
              name: prometheus
              protocol: TCP
          # env:
          #   - name: SPRING_PROFILES_ACTIVE
          #     value: openshift
      volumes:
      - configMap:
          defaultMode: 420
          name: leaf1
        name: leaf1-volume
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: leaf1
  name: leaf1
  namespace: networkpolicy-leaf1
spec:
  ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 8080
  selector:
    app: leaf1
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: leaf1
  name: leaf1
  namespace: networkpolicy-leaf1
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: leaf1
    weight: 100
  wildcardPolicy: None
---
apiVersion: v1
data:
  application.properties: |-
    spring.application.name=leaf1
    server.port=8080
    management.endpoints.web.exposure.include=*
    leaf2.hostname=leaf2.networkpolicy-leaf2.svc
    leaf2.portnum=8080
    opentracing.jaeger.enabled=false
kind: ConfigMap
metadata:
  name: leaf1
  namespace: networkpolicy-leaf1
