apiVersion: project.openshift.io/v1
kind: ProjectRequest
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: ""
  name: networkpolicy-leaf1
  namespace: networkpolicy-leaf1